### ISSUE TITLE
Can work with Metin2?

### ISSUE THREAD

**Issue by youssefuwk55** [hatz2/GflessClient#10]
Hello,

- If I change the gameEnvironmentId  and platformGameId that exist in nostalauth.cpp file to metin2 platform and environment ID, it will  create a metin2 accounts instead of nostale? and What is the version of Qt used to compile the launcher?

Regards,

**Comment by hatz2** [comment]
It is worth giving a try, it should probably work nevertheless I don't know if you can achieve that 100% because I have never looked at how metin2 login protocol works. The launcher was compiled with QT 6.5.1 and MSVC2019 64 Bit compiler.

**Comment by youssefuwk55** [comment]
I tried but it give me this error.
![Capture](https://github.com/user-attachments/assets/fec9b3ae-3f3d-4bd8-a717-79c59ce5ef97)

Can you help me to fix this error?
Thanks in advance!

**Comment by youssefuwk55** [comment]
Also I tried to change InstallationId from registry and change my IP without using GFlessClient to bypass the restricted policy that prevent me to create more than 3 accounts per day, but I fail. Is there anything else I should do?

**Comment by hatz2** [comment]
It's either you are restricted to create more accounts or the request is not valid. I would recommend you to check the request sent by the gameforge client itself against the one sent by the gfless client using an http debugger like fiddler or http debugger pro.

**Comment by youssefuwk55** [comment]
Thank you for paying attention, unfortunately the request is not valid due  to the difference between Nostale and Metin2 Https request. 
I have a question ,please.  I changed my IP and InstallationId, but gameforge still prevent me to create an account. Is there anything else I should do to solve this issue?

**Comment by hatz2** [comment]
I don't know what parameters the gf launcher takes into consideration when creating a new account, you can try modifying the parameters in your identity.json file so that the blackbox generated is different
