### ISSUE TITLE
GFClient update

### ISSUE THREAD

**Issue by SoNiice** [hatz2/GflessClient#8]
Hey!

The GFClient had an update like 2 weeks ago changing the auth system and security of the client, I tried figuring out what changed but everything looked quite normal to me, the blackbox token logic is still the same, I didn't see any new data decrypting it, neither did I see any request changes but still it doesn't work anymore, maybe you'll find out having more experience with the GFClient overall.

Cheers

**Comment by SoNiice** [comment]
@hatz2 I saw you did an update post on elitepvpers, for the authentication you're simply in need of some new request headers, for the iovation I'm still stuck sadly, jfyi

**Comment by hatz2** [comment]
You are right, auth isn't a problem to me either but im also stuck at iovation. I have tried sending all the event requests using the custom embedded certificate inside the gfclient but still the server responds with 403. I also noticed that if you use, for example http debugger pro, you are able to see the request to auth/iovation without errors but if you try to resend it the server will reply with 403. Before the update it was possible to resend the request and the server would reply with 200.

**Comment by SoNiice** [comment]
> @SoNiice You are right, auth isn't a problem to me either but im also stuck at iovation. I have tried sending all the event requests using the custom embedded certificate inside the gfclient but still the server responds with 403. I also noticed that if you use, for example http debugger pro, you are able to see the request to auth/iovation without errors but if you try to resend it the server will reply with 403. Before the update it was possible to resend the request and the server would reply with 200.

I actually didn't know HTTP Debugger Pro is not using a proxy to intercept with requests, that helps indeed. The gfclient added a check which we figured out by debugging that uses the **winapi** (_winhttp.h_) to check on your current system users proxy settings using **WinHttpGetIEProxyConfigForCurrentUser** - So yea, using a non proxied tool actually helps atleast, ty for hint.

**Comment by hatz2** [comment]
> > @SoNiice You are right, auth isn't a problem to me either but im also stuck at iovation. I have tried sending all the event requests using the custom embedded certificate inside the gfclient but still the server responds with 403. I also noticed that if you use, for example http debugger pro, you are able to see the request to auth/iovation without errors but if you try to resend it the server will reply with 403. Before the update it was possible to resend the request and the server would reply with 200.
> 
> I actually didn't know HTTP Debugger Pro is not using a proxy to intercept with requests, that helps indeed. The gfclient added a check which we figured out by debugging that uses the **winapi** (_winhttp.h_) to check on your current system users proxy settings using **WinHttpGetIEProxyConfigForCurrentUser** - So yea, using a non proxied tool actually helps atleast, ty for hint.

Not yet but I'll investigate it when I have time.

**Comment by hatz2** [comment]
Working again
